# Generated by Django 4.1 on 2024-03-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='dogs',
        ),
    ]
